name: brain2text
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pandas=2.2.3
  - numpy=1.26.4
  - scikit-learn=1.4.2
  - pytorch::pytorch=2.3.0
  - pip:
      - transformers==4.43.0
      - tqdm==4.66.4
      - matplotlib==3.8.4
